CREATE TABLE alameda (
    ID INT PRIMARY KEY,
    ParcelId INT,
    LotNumber VARCHAR(50),
    BlockNumber VARCHAR(50),
    SurveyPlan VARCHAR(100),
    Claimant VARCHAR(255),
    BarangayNa VARCHAR(255),
    Area DOUBLE,
    IsValidate TINYINT(1),
    Application VARCHAR(50),
    PlaCount INT,
    ApplicantN VARCHAR(255),
    IsApproved TINYINT(1),
    IsReconstr TINYINT(1),
    Verified TINYINT(1),
    IsDocument TINYINT(1),
    ProjectId INT,
    ParcelSour INT,
    BarangayCo VARCHAR(50),
    TiePointId INT,
    TiePointNa VARCHAR(255),
    Municipality VARCHAR(50),
    Municipal1 VARCHAR(255),
    LotStatus VARCHAR(100),
    TypeI INT,
    BranchesI INT,
    Coordinate INT,
    XI DOUBLE,
    YI DOUBLE,
    LongitudeI DOUBLE,
    LatitudeI DOUBLE,
    LengthI DOUBLE,
    AreaI DOUBLE,
    BearingI DOUBLE,
    SelectionM INT,
    SelectionI INT,
    VersionI INT,
    geometry JSON
);
commit;