CREATE TABLE tax_forms (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, 
  arpNo VARCHAR(50),
  tdPrinted BOOLEAN,
  municipalCode BOOLEAN,
  accountNo VARCHAR(50),
  ownerName VARCHAR(100),
  ownerAddress VARCHAR(255),
  administrator VARCHAR(100),
  adminAddress VARCHAR(255),
  north VARCHAR(100),
  east VARCHAR(100),
  south VARCHAR(100),
  west VARCHAR(100),
  propertyIndexNo VARCHAR(50),
  subdivision VARCHAR(100),
  phase VARCHAR(50),
  lotNo VARCHAR(50),
  tdPrintedNo VARCHAR(50),
  houseNo VARCHAR(50),
  street VARCHAR(100),
  landmark VARCHAR(100),
  barangay VARCHAR(100),
  barangayOnPrint BOOLEAN,
  barangayText VARCHAR(100),
  octNo VARCHAR(50),
  dated DATE,
  surveyNo VARCHAR(50),
  cadLotNo VARCHAR(50),
  lotNo2 VARCHAR(50),
  blockNo VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1000;
commit;